# Generated by Django 5.0.6 on 2024-12-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
